### PR TITLE
Add automatic theme (syncs with system settings)

### PR DESCRIPTION
**Pull request by Bleuzen**
Hi :)
This adds an option to follow the systems color theme. If theme is changed in system settings, HTTP Toolkit will automatically adapt (if enabled).

### CODE REVIEW

**Comment by Bleuzen** [comment]
> Was there a reason you didn't add this as another tab in the theme options?

Was, yeah. Had it as tab first but it was buggy sometimes under circumstances.
Note: I usually don't work with some stuff used in httptoolkit, so I probably just made a weird mistake with mobx or something.

Anyway, I gave it another try and it works this time. Will push now...

**Comment by Bleuzen** [comment]
I'm not perfectly happy with the icon yet, didn't find a simple one for automatic and `adjust` is already used for the high contrast theme, so went with `magic` for now.
@pimterry if you have a better idea, go ahead.

**Review by pimterry — APPROVED** [review]

**Comment by pimterry** [comment]
Great stuff, thanks @Bleuzen! Looks perfect to me :+1:

By the way, in case you're not aware, HTTP Toolkit Pro is totally free for contributors. If you're interested, just let me know your email address (here or send me a message at tim @ httptoolkit.com) and I'll set you up.

**Comment by Bleuzen** [comment]
@pimterry Cool, you're welcome.

Sounds good, thanks for the offer. I sent you an email.

**Pull request merged**
