### PR TITLE
Run on windows

### LINKED ISSUE #59: `npm start` doesn't work on Windows
I was trying to compile/run this repo following the instructions in the README, but I'm getting a lot of errors that I'm not sure how to deal with. I'm not sure exactly what I'm doing wrong.

I'm on Windows. I cloned the repo and ran `npm install`. 

Running `npm start` yields:

```
> httptoolkit-ui@0.1.0 start
> ./node_modules/httptoolkit-server/bin/run start & npm run start:web

'.' is not recognized as an internal or external command,
operable program or batch file.

> httptoolkit-ui@0.1.0 start:web
> env-cmd -f ./automation/ts-node.env webpack-dev-server --config ./automation/webpack.dev.ts

i ｢wds｣: Project is running at http://local.httptoolkit.tech:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\Noam\Desktop\httptoolkit-ui-master\dist
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: Hash: 9685bf8b84bc1511f2ab
Version: webpack 4.46.0
Time: 33958ms
Built at: 11/08/2022 3:27:59 PM
i ｢wdm｣: Compiled successfully.
No issues found.

```

When opening the actual local.httptoolkit.tech:8080 site in the browser (Firefox), it displays the "This is taking longer than normal" message, and a whole bunch and a bunch of errors appear in the console, including the following:

<details>
  <summary>Error messages</summary>
  
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:45456/start. (Reason: CORS request did not succeed). Status code: (null).
```

```
proxy-store.ts:55
Server initialization failed TypeError: NetworkError when attempting to fetch resource.
```

```
index.tsx:66
Service worker not supported, oh well, no autoupdating for you.
```

```
index.tsx:129
Previous server version was null
```

```
errors.ts:55
Reporting error: Error: Failed to initialize application
    <anonymous> index.tsx:131
    fulfilled index.tsx:31
    promise callback*step index.tsx:33
    __awaiter index.tsx:34
    __awaiter index.tsx:30
    <anonymous> index.tsx:128
    promise callback* index.tsx:128
    tsx app.js:27449
    __webpack_require__ app.js:105
    0 app.js:28277
    __webpack_require__ app.js:105
    <anonymous> app.js:275
    <anonymous> app.js:278
```
</details>

So it seems like the server isn't being run because of the first error, and I would then assume that all of the browser console errors are because the server isn't running. The error `'.' is not recognized as an internal or external command, operable program or batch file.` seems to indicate that this repo isn't set up to be run on Windows. Do I need to develop on Linux?

### PR DESCRIPTION
**Pull request by lord-ne**
Update package.json to allow running on Windows (Closes #59)

Some of the tests still don't seem to work on Windows (seems like it's having trouble finding Chrome), and `bundle-stats:build` might also have some issues on Windows (using PowerShell instead of the `tail` command seems to be too slow), but it's mostly working

### CODE REVIEW

**Comment by lord-ne** [comment]
Should I not be pushing `package-lock.json`? Seems like there's way too many diffs

**Comment by pimterry** [comment]
> Should I not be pushing package-lock.json? Seems like there's way too many diffs

No, it's good, I think the diff is fine - I've looked through and it looks like it's just the subdependencies for the two new packages, plus minor version bumps on other related packages.

**Comment by pimterry** [comment]
Thanks for this! Nice tidy fix. All seems to be working nicely for me.

By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors ([more info](https://github.com/httptoolkit/httptoolkit#contributing-directly)). I've enabled a year of Pro linked to the email from your GitHub commits (n######l@g####.com). Just click 'Get Pro' in the app, then 'Log into existing account' and enter your email to use it :smile:. Thanks again!

**Comment by lord-ne** [comment]
> By the way, in case you're not aware, HTTP Toolkit Pro is free for contributors ([more info](https://github.com/httptoolkit/httptoolkit#contributing-directly))

Oh nice, that's a really cool system.

**Pull request merged**
